/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol

// Source: schema.json
export type SiteSettings = {
  _id: string
  _type: 'siteSettings'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  navigation?: Array<
    {
      _key: string
    } & NavItem
  >
}

export type ReleaseReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'release'
}

export type ArtistReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'artist'
}

export type LabelReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'label'
}

export type ReleasesPageReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'releasesPage'
}

export type PageReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'page'
}

export type ButtonBlock = {
  _type: 'buttonBlock'
  label: string
  variant?: 'default' | 'outline' | 'secondary' | 'ghost' | 'link' | 'destructive'
  size?: 'default' | 'sm' | 'lg' | 'icon'
  linkType: 'internal' | 'external'
  internalLink?:
    | ReleaseReference
    | ArtistReference
    | LabelReference
    | ReleasesPageReference
    | PageReference
  externalUrl?: string
}

export type NavItem = {
  _type: 'navItem'
  label: string
  linkType: 'internal' | 'external'
  internalLink?:
    | ReleaseReference
    | ArtistReference
    | LabelReference
    | ReleasesPageReference
    | PageReference
  externalUrl?: string
}

export type Page = {
  _id: string
  _type: 'page'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  slug: Slug
  pageBuilder?: Array<
    | ({
        _key: string
      } & ButtonBlock)
    | ({
        _key: string
      } & ImageWithAlt)
  >
  seo?: Seo
}

export type Seo = {
  _type: 'seo'
  metaTitle?: string
  metaDescription?: string
  ogImage?: ImageWithAlt
  noIndex?: boolean
}

export type Slug = {
  _type: 'slug'
  current: string
  source?: string
}

export type ReleasesPage = {
  _id: string
  _type: 'releasesPage'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  intro?: string
  seo?: Seo
}

export type Release = {
  _id: string
  _type: 'release'
  _createdAt: string
  _updatedAt: string
  _rev: string
  artist: ArtistReference
  releaseName: string
  slug: Slug
  mediaType: 'vinyl' | 'shellac' | 'cd' | 'cassette'
  classification: 'LP' | 'EP' | 'Single'
  speed?: '33' | '45' | '78'
  size?: '7"' | '10"' | '12"'
  channels?: 'mono' | 'stereo'
  descriptions?: Array<string>
  cover?: ImageWithAlt
  gallery?: Array<
    {
      _key: string
    } & ImageWithAlt
  >
  discs?: Array<{
    discNumber: number
    name?: string
    tracks?: Array<{
      position: string
      title: string
      _key: string
    }>
    _key: string
  }>
  dateUnknown?: boolean
  datePrecision?: 'year' | 'month' | 'day'
  releaseYear?: number
  releaseMonth?: '01' | '02' | '03' | '04' | '05' | '06' | '07' | '08' | '09' | '10' | '11' | '12'
  releaseDay?: number
  noLabel?: boolean
  label?: LabelReference
  discogs?: {
    releaseId?: number
    masterId?: number
  }
}

export type Label = {
  _id: string
  _type: 'label'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name: string
  slug: Slug
  cover?: ImageWithAlt
  gallery?: Array<
    {
      _key: string
    } & ImageWithAlt
  >
}

export type SanityImageAssetReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
}

export type ImageWithAlt = {
  _type: 'imageWithAlt'
  asset?: SanityImageAssetReference
  media?: unknown
  hotspot?: SanityImageHotspot
  crop?: SanityImageCrop
  alt: string
  caption?: string
}

export type Artist = {
  _id: string
  _type: 'artist'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name: string
  slug: Slug
  cover?: ImageWithAlt
  gallery?: Array<
    {
      _key: string
    } & ImageWithAlt
  >
}

export type SanityImageCrop = {
  _type: 'sanity.imageCrop'
  top: number
  bottom: number
  left: number
  right: number
}

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot'
  x: number
  y: number
  height: number
  width: number
}

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch'
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: 'sanity.imagePalette'
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions'
  height: number
  width: number
  aspectRatio: number
}

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata'
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  thumbHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type SanityFileAsset = {
  _id: string
  _type: 'sanity.fileAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash: string
  extension: string
  mimeType: string
  size: number
  assetId: string
  uploadId?: string
  path: string
  url: string
  source?: SanityAssetSourceData
}

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData'
  name?: string
  id?: string
  url?: string
}

export type SanityImageAsset = {
  _id: string
  _type: 'sanity.imageAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash: string
  extension: string
  mimeType: string
  size: number
  assetId: string
  uploadId?: string
  path: string
  url: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type Geopoint = {
  _type: 'geopoint'
  lat?: number
  lng?: number
  alt?: number
}

export type AllSanitySchemaTypes =
  | SiteSettings
  | ReleaseReference
  | ArtistReference
  | LabelReference
  | ReleasesPageReference
  | PageReference
  | ButtonBlock
  | NavItem
  | Page
  | Seo
  | Slug
  | ReleasesPage
  | Release
  | Label
  | SanityImageAssetReference
  | ImageWithAlt
  | Artist
  | SanityImageCrop
  | SanityImageHotspot
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint

// Source: ../web/sanity/queries.ts
// Variable: SITE_SETTINGS_QUERY
// Query: *[_id == "siteSettings"][0]{    title,    "navigation": coalesce(navigation, [])[]{      _key,      label,      linkType,      externalUrl,      "internal": internalLink->{  _type,  "slug": slug.current}    }  }
export type SITE_SETTINGS_QUERY_RESULT =
  | {
      title: null
      navigation: Array<never>
    }
  | {
      title: string
      navigation: Array<never>
    }
  | {
      title: string | null
      navigation: Array<never>
    }
  | {
      title: string
      navigation:
        | Array<{
            _key: string
            label: string
            linkType: 'external' | 'internal'
            externalUrl: string | null
            internal:
              | {
                  _type: 'artist'
                  slug: string
                }
              | {
                  _type: 'label'
                  slug: string
                }
              | {
                  _type: 'page'
                  slug: string
                }
              | {
                  _type: 'release'
                  slug: string
                }
              | {
                  _type: 'releasesPage'
                  slug: null
                }
              | null
          }>
        | Array<never>
    }
  | null

// Source: ../web/sanity/queries.ts
// Variable: RELEASES_PAGE_QUERY
// Query: *[_id == "releasesPage"][0]{    title,    intro,      seo{    metaTitle,    metaDescription,    noIndex,    ogImage{  asset,  hotspot,  crop,  alt}  }  }
export type RELEASES_PAGE_QUERY_RESULT =
  | {
      title: null
      intro: null
      seo: null
    }
  | {
      title: string
      intro: null
      seo: null
    }
  | {
      title: string | null
      intro: null
      seo: null
    }
  | {
      title: string
      intro: null
      seo: {
        metaTitle: string | null
        metaDescription: string | null
        noIndex: boolean | null
        ogImage: {
          asset: SanityImageAssetReference | null
          hotspot: SanityImageHotspot | null
          crop: SanityImageCrop | null
          alt: string
        } | null
      } | null
    }
  | {
      title: string
      intro: string | null
      seo: {
        metaTitle: string | null
        metaDescription: string | null
        noIndex: boolean | null
        ogImage: {
          asset: SanityImageAssetReference | null
          hotspot: SanityImageHotspot | null
          crop: SanityImageCrop | null
          alt: string
        } | null
      } | null
    }
  | null

// Source: ../web/sanity/queries.ts
// Variable: HOME_RELEASES_QUERY
// Query: *[_type == "release" && defined(slug.current)]    | order(coalesce(releaseYear, 0) desc)    [0...12]{        _id,  _type,    releaseName,  "slug": slug.current,  classification,  releaseYear,  dateUnknown,  cover{  asset,  hotspot,  crop,  alt},    "artist": artist->{name, "slug": slug.current}    }
export type HOME_RELEASES_QUERY_RESULT = Array<{
  _id: string
  _type: 'release'
  releaseName: string
  slug: string
  classification: 'EP' | 'LP' | 'Single'
  releaseYear: number | null
  dateUnknown: boolean | null
  cover: {
    asset: SanityImageAssetReference | null
    hotspot: SanityImageHotspot | null
    crop: SanityImageCrop | null
    alt: string
  } | null
  artist: {
    name: string
    slug: string
  }
}>

// Source: ../web/sanity/queries.ts
// Variable: RELEASES_QUERY
// Query: *[_type == "release" && defined(slug.current)]    | order(coalesce(releaseYear, 0) desc){        _id,  _type,    releaseName,  "slug": slug.current,  classification,  releaseYear,  dateUnknown,  cover{  asset,  hotspot,  crop,  alt},    "artist": artist->{name, "slug": slug.current}    }
export type RELEASES_QUERY_RESULT = Array<{
  _id: string
  _type: 'release'
  releaseName: string
  slug: string
  classification: 'EP' | 'LP' | 'Single'
  releaseYear: number | null
  dateUnknown: boolean | null
  cover: {
    asset: SanityImageAssetReference | null
    hotspot: SanityImageHotspot | null
    crop: SanityImageCrop | null
    alt: string
  } | null
  artist: {
    name: string
    slug: string
  }
}>

// Source: ../web/sanity/queries.ts
// Variable: RELEASE_SLUGS_QUERY
// Query: *[_type == "release" && defined(slug.current)][].slug.current
export type RELEASE_SLUGS_QUERY_RESULT = Array<string>

// Source: ../web/sanity/queries.ts
// Variable: RELEASE_QUERY
// Query: *[_type == "release" && slug.current == $slug][0]{    _id,    _type,    releaseName,    "slug": slug.current,    classification,    mediaType,    speed,    size,    channels,    descriptions,    releaseYear,    dateUnknown,    noLabel,    "artist": artist->{name, "slug": slug.current},    "label": label->{name, "slug": slug.current},    cover{  asset,  hotspot,  crop,  alt,  caption},    gallery[{  _key,  asset,  hotspot,  crop,  alt,  caption}],    discs[]{      _key,      discNumber,      name,      tracks[]{_key, position, title}    },    discogs{releaseId, masterId}  }
export type RELEASE_QUERY_RESULT = {
  _id: string
  _type: 'release'
  releaseName: string
  slug: string
  classification: 'EP' | 'LP' | 'Single'
  mediaType: 'cassette' | 'cd' | 'shellac' | 'vinyl'
  speed: '33' | '45' | '78' | null
  size: '10"' | '12"' | '7"' | null
  channels: 'mono' | 'stereo' | null
  descriptions: Array<string> | null
  releaseYear: number | null
  dateUnknown: boolean | null
  noLabel: boolean | null
  artist: {
    name: string
    slug: string
  }
  label: {
    name: string
    slug: string
  } | null
  cover: {
    asset: SanityImageAssetReference | null
    hotspot: SanityImageHotspot | null
    crop: SanityImageCrop | null
    alt: string
    caption: string | null
  } | null
  gallery: Array<never> | null
  discs: Array<{
    _key: string
    discNumber: number
    name: string | null
    tracks: Array<{
      _key: string
      position: string
      title: string
    }> | null
  }> | null
  discogs: {
    releaseId: number | null
    masterId: number | null
  } | null
} | null

// Source: ../web/sanity/queries.ts
// Variable: ARTIST_SLUGS_QUERY
// Query: *[_type == "artist" && defined(slug.current)][].slug.current
export type ARTIST_SLUGS_QUERY_RESULT = Array<string>

// Source: ../web/sanity/queries.ts
// Variable: ARTIST_QUERY
// Query: *[_type == "artist" && slug.current == $slug][0]{    _id,    _type,    name,    "slug": slug.current,    cover{  asset,  hotspot,  crop,  alt,  caption},    gallery[{  _key,  asset,  hotspot,  crop,  alt,  caption}],    "releases": *[_type == "release" && artist._ref == ^._id && defined(slug.current)]      | order(coalesce(releaseYear, 0) desc){          _id,    releaseName,  "slug": slug.current,  classification,  releaseYear,  dateUnknown,  cover{  asset,  hotspot,  crop,  alt}      }  }
export type ARTIST_QUERY_RESULT = {
  _id: string
  _type: 'artist'
  name: string
  slug: string
  cover: {
    asset: SanityImageAssetReference | null
    hotspot: SanityImageHotspot | null
    crop: SanityImageCrop | null
    alt: string
    caption: string | null
  } | null
  gallery: Array<never> | null
  releases: Array<{
    _id: string
    releaseName: string
    slug: string
    classification: 'EP' | 'LP' | 'Single'
    releaseYear: number | null
    dateUnknown: boolean | null
    cover: {
      asset: SanityImageAssetReference | null
      hotspot: SanityImageHotspot | null
      crop: SanityImageCrop | null
      alt: string
    } | null
  }>
} | null

// Source: ../web/sanity/queries.ts
// Variable: LABEL_SLUGS_QUERY
// Query: *[_type == "label" && defined(slug.current)][].slug.current
export type LABEL_SLUGS_QUERY_RESULT = Array<string>

// Source: ../web/sanity/queries.ts
// Variable: PAGE_SLUGS_QUERY
// Query: *[_type == "page" && defined(slug.current)][].slug.current
export type PAGE_SLUGS_QUERY_RESULT = Array<string>

// Source: ../web/sanity/queries.ts
// Variable: PAGE_QUERY
// Query: *[_type == "page" && slug.current == $slug][0]{    title,    pageBuilder[]{      _key,      _type,      label,      variant,      size,      linkType,      externalUrl,      "internalLink": internalLink->{  _type,  "slug": slug.current},      asset,      hotspot,      crop,      alt,      caption    },      seo{    metaTitle,    metaDescription,    noIndex,    ogImage{  asset,  hotspot,  crop,  alt}  }  }
export type PAGE_QUERY_RESULT = {
  title: string
  pageBuilder: Array<
    | {
        _key: string
        _type: 'buttonBlock'
        label: string
        variant: 'default' | 'destructive' | 'ghost' | 'link' | 'outline' | 'secondary' | null
        size: 'default' | 'icon' | 'lg' | 'sm' | null
        linkType: 'external' | 'internal'
        externalUrl: string | null
        internalLink:
          | {
              _type: 'artist'
              slug: string
            }
          | {
              _type: 'label'
              slug: string
            }
          | {
              _type: 'page'
              slug: string
            }
          | {
              _type: 'release'
              slug: string
            }
          | {
              _type: 'releasesPage'
              slug: null
            }
          | null
        asset: null
        hotspot: null
        crop: null
        alt: null
        caption: null
      }
    | {
        _key: string
        _type: 'imageWithAlt'
        label: null
        variant: null
        size: null
        linkType: null
        externalUrl: null
        internalLink: null
        asset: SanityImageAssetReference | null
        hotspot: SanityImageHotspot | null
        crop: SanityImageCrop | null
        alt: string
        caption: string | null
      }
  > | null
  seo: {
    metaTitle: string | null
    metaDescription: string | null
    noIndex: boolean | null
    ogImage: {
      asset: SanityImageAssetReference | null
      hotspot: SanityImageHotspot | null
      crop: SanityImageCrop | null
      alt: string
    } | null
  } | null
} | null

// Source: ../web/sanity/queries.ts
// Variable: LABEL_QUERY
// Query: *[_type == "label" && slug.current == $slug][0]{    _id,    _type,    name,    "slug": slug.current,    cover{  asset,  hotspot,  crop,  alt,  caption},    gallery[{  _key,  asset,  hotspot,  crop,  alt,  caption}],    "releases": *[_type == "release" && label._ref == ^._id && defined(slug.current)]      | order(coalesce(releaseYear, 0) desc){          _id,    releaseName,  "slug": slug.current,  classification,  releaseYear,  dateUnknown,  cover{  asset,  hotspot,  crop,  alt},    "artist": artist->{name, "slug": slug.current}      }  }
export type LABEL_QUERY_RESULT = {
  _id: string
  _type: 'label'
  name: string
  slug: string
  cover: {
    asset: SanityImageAssetReference | null
    hotspot: SanityImageHotspot | null
    crop: SanityImageCrop | null
    alt: string
    caption: string | null
  } | null
  gallery: Array<never> | null
  releases: Array<{
    _id: string
    releaseName: string
    slug: string
    classification: 'EP' | 'LP' | 'Single'
    releaseYear: number | null
    dateUnknown: boolean | null
    cover: {
      asset: SanityImageAssetReference | null
      hotspot: SanityImageHotspot | null
      crop: SanityImageCrop | null
      alt: string
    } | null
    artist: {
      name: string
      slug: string
    }
  }>
} | null

// Query TypeMap
import '@sanity/client'
declare module '@sanity/client' {
  interface SanityQueries {
    '\n  *[_id == "siteSettings"][0]{\n    title,\n    "navigation": coalesce(navigation, [])[]{\n      _key,\n      label,\n      linkType,\n      externalUrl,\n      "internal": internalLink->{\n  _type,\n  "slug": slug.current\n}\n    }\n  }\n': SITE_SETTINGS_QUERY_RESULT
    '\n  *[_id == "releasesPage"][0]{\n    title,\n    intro,\n    \n  seo{\n    metaTitle,\n    metaDescription,\n    noIndex,\n    ogImage{\n  asset,\n  hotspot,\n  crop,\n  alt\n}\n  }\n\n  }\n': RELEASES_PAGE_QUERY_RESULT
    '\n  *[_type == "release" && defined(slug.current)]\n    | order(coalesce(releaseYear, 0) desc)\n    [0...12]{\n      \n  _id,\n  _type,\n  \n  releaseName,\n  "slug": slug.current,\n  classification,\n  releaseYear,\n  dateUnknown,\n  cover{\n  asset,\n  hotspot,\n  crop,\n  alt\n}\n,\n  \n  "artist": artist->{name, "slug": slug.current}\n\n\n    }\n': HOME_RELEASES_QUERY_RESULT
    '\n  *[_type == "release" && defined(slug.current)]\n    | order(coalesce(releaseYear, 0) desc){\n      \n  _id,\n  _type,\n  \n  releaseName,\n  "slug": slug.current,\n  classification,\n  releaseYear,\n  dateUnknown,\n  cover{\n  asset,\n  hotspot,\n  crop,\n  alt\n}\n,\n  \n  "artist": artist->{name, "slug": slug.current}\n\n\n    }\n': RELEASES_QUERY_RESULT
    '\n  *[_type == "release" && defined(slug.current)][].slug.current\n': RELEASE_SLUGS_QUERY_RESULT
    '\n  *[_type == "release" && slug.current == $slug][0]{\n    _id,\n    _type,\n    releaseName,\n    "slug": slug.current,\n    classification,\n    mediaType,\n    speed,\n    size,\n    channels,\n    descriptions,\n    releaseYear,\n    dateUnknown,\n    noLabel,\n    "artist": artist->{name, "slug": slug.current},\n    "label": label->{name, "slug": slug.current},\n    cover{\n  asset,\n  hotspot,\n  crop,\n  alt\n,\n  caption},\n    gallery[{\n  _key,\n  asset,\n  hotspot,\n  crop,\n  alt,\n  caption\n}],\n    discs[]{\n      _key,\n      discNumber,\n      name,\n      tracks[]{_key, position, title}\n    },\n    discogs{releaseId, masterId}\n  }\n': RELEASE_QUERY_RESULT
    '\n  *[_type == "artist" && defined(slug.current)][].slug.current\n': ARTIST_SLUGS_QUERY_RESULT
    '\n  *[_type == "artist" && slug.current == $slug][0]{\n    _id,\n    _type,\n    name,\n    "slug": slug.current,\n    cover{\n  asset,\n  hotspot,\n  crop,\n  alt\n,\n  caption},\n    gallery[{\n  _key,\n  asset,\n  hotspot,\n  crop,\n  alt,\n  caption\n}],\n    "releases": *[_type == "release" && artist._ref == ^._id && defined(slug.current)]\n      | order(coalesce(releaseYear, 0) desc){\n        \n  _id,\n  \n  releaseName,\n  "slug": slug.current,\n  classification,\n  releaseYear,\n  dateUnknown,\n  cover{\n  asset,\n  hotspot,\n  crop,\n  alt\n}\n\n\n      }\n  }\n': ARTIST_QUERY_RESULT
    '\n  *[_type == "label" && defined(slug.current)][].slug.current\n': LABEL_SLUGS_QUERY_RESULT
    '\n  *[_type == "page" && defined(slug.current)][].slug.current\n': PAGE_SLUGS_QUERY_RESULT
    '\n  *[_type == "page" && slug.current == $slug][0]{\n    title,\n    pageBuilder[]{\n      _key,\n      _type,\n      label,\n      variant,\n      size,\n      linkType,\n      externalUrl,\n      "internalLink": internalLink->{\n  _type,\n  "slug": slug.current\n},\n      asset,\n      hotspot,\n      crop,\n      alt,\n      caption\n    },\n    \n  seo{\n    metaTitle,\n    metaDescription,\n    noIndex,\n    ogImage{\n  asset,\n  hotspot,\n  crop,\n  alt\n}\n  }\n\n  }\n': PAGE_QUERY_RESULT
    '\n  *[_type == "label" && slug.current == $slug][0]{\n    _id,\n    _type,\n    name,\n    "slug": slug.current,\n    cover{\n  asset,\n  hotspot,\n  crop,\n  alt\n,\n  caption},\n    gallery[{\n  _key,\n  asset,\n  hotspot,\n  crop,\n  alt,\n  caption\n}],\n    "releases": *[_type == "release" && label._ref == ^._id && defined(slug.current)]\n      | order(coalesce(releaseYear, 0) desc){\n        \n  _id,\n  \n  releaseName,\n  "slug": slug.current,\n  classification,\n  releaseYear,\n  dateUnknown,\n  cover{\n  asset,\n  hotspot,\n  crop,\n  alt\n}\n,\n  \n  "artist": artist->{name, "slug": slug.current}\n\n\n      }\n  }\n': LABEL_QUERY_RESULT
  }
}
