/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol

// Source: schema.json
export type SiteSettings = {
  _id: string
  _type: 'siteSettings'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  navigation?: Array<
    {
      _key: string
    } & NavItem
  >
}

export type ReleaseReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'release'
}

export type ArtistReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'artist'
}

export type LabelReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'label'
}

export type ReleasesPageReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'releasesPage'
}

export type NavItem = {
  _type: 'navItem'
  label: string
  linkType: 'internal' | 'external'
  internalLink?: ReleaseReference | ArtistReference | LabelReference | ReleasesPageReference
  externalUrl?: string
}

export type ReleasesPage = {
  _id: string
  _type: 'releasesPage'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  intro?: string
  seo?: Seo
}

export type Seo = {
  _type: 'seo'
  metaTitle?: string
  metaDescription?: string
  ogImage?: ImageWithAlt
  noIndex?: boolean
}

export type Release = {
  _id: string
  _type: 'release'
  _createdAt: string
  _updatedAt: string
  _rev: string
  artist: ArtistReference
  releaseName: string
  slug: Slug
  format: 'LP' | 'EP' | 'Single'
  speed: '33' | '45' | '78'
  cover?: ImageWithAlt
  gallery?: Array<
    {
      _key: string
    } & ImageWithAlt
  >
  discs?: Array<{
    discNumber: number
    name?: string
    tracks?: Array<{
      position: string
      title: string
      _key: string
    }>
    _key: string
  }>
  dateUnknown?: boolean
  releaseDate?: string
  noLabel?: boolean
  label?: LabelReference
  discogs?: {
    releaseId?: number
    masterId?: number
  }
}

export type Label = {
  _id: string
  _type: 'label'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name: string
  slug: Slug
  cover?: ImageWithAlt
  gallery?: Array<
    {
      _key: string
    } & ImageWithAlt
  >
}

export type SanityImageAssetReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
}

export type ImageWithAlt = {
  _type: 'imageWithAlt'
  asset?: SanityImageAssetReference
  media?: unknown
  hotspot?: SanityImageHotspot
  crop?: SanityImageCrop
  alt: string
  caption?: string
}

export type Slug = {
  _type: 'slug'
  current: string
  source?: string
}

export type Artist = {
  _id: string
  _type: 'artist'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name: string
  slug: Slug
  cover?: ImageWithAlt
  gallery?: Array<
    {
      _key: string
    } & ImageWithAlt
  >
}

export type SanityImageCrop = {
  _type: 'sanity.imageCrop'
  top: number
  bottom: number
  left: number
  right: number
}

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot'
  x: number
  y: number
  height: number
  width: number
}

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch'
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: 'sanity.imagePalette'
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions'
  height: number
  width: number
  aspectRatio: number
}

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata'
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  thumbHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type SanityFileAsset = {
  _id: string
  _type: 'sanity.fileAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash: string
  extension: string
  mimeType: string
  size: number
  assetId: string
  uploadId?: string
  path: string
  url: string
  source?: SanityAssetSourceData
}

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData'
  name?: string
  id?: string
  url?: string
}

export type SanityImageAsset = {
  _id: string
  _type: 'sanity.imageAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash: string
  extension: string
  mimeType: string
  size: number
  assetId: string
  uploadId?: string
  path: string
  url: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type Geopoint = {
  _type: 'geopoint'
  lat?: number
  lng?: number
  alt?: number
}

export type AllSanitySchemaTypes =
  | SiteSettings
  | ReleaseReference
  | ArtistReference
  | LabelReference
  | ReleasesPageReference
  | NavItem
  | ReleasesPage
  | Seo
  | Release
  | Label
  | SanityImageAssetReference
  | ImageWithAlt
  | Slug
  | Artist
  | SanityImageCrop
  | SanityImageHotspot
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint

// Source: ../web/sanity/queries.ts
// Variable: SITE_SETTINGS_QUERY
// Query: *[_id == "siteSettings"][0]{    title,    "navigation": coalesce(navigation, [])[]{      _key,      label,      linkType,      externalUrl,      "internal": internalLink->{        _type,        "slug": slug.current      }    }  }
export type SITE_SETTINGS_QUERY_RESULT =
  | {
      title: null
      navigation: Array<never>
    }
  | {
      title: string
      navigation: Array<never>
    }
  | {
      title: string | null
      navigation: Array<never>
    }
  | {
      title: string
      navigation:
        | Array<{
            _key: string
            label: string
            linkType: 'external' | 'internal'
            externalUrl: string | null
            internal:
              | {
                  _type: 'artist'
                  slug: string
                }
              | {
                  _type: 'label'
                  slug: string
                }
              | {
                  _type: 'release'
                  slug: string
                }
              | {
                  _type: 'releasesPage'
                  slug: null
                }
              | null
          }>
        | Array<never>
    }
  | null

// Source: ../web/sanity/queries.ts
// Variable: RELEASES_PAGE_QUERY
// Query: *[_id == "releasesPage"][0]{    title,    intro,    seo{      metaTitle,      metaDescription,      noIndex,      ogImage{        asset,        hotspot,        crop,        alt      }    }  }
export type RELEASES_PAGE_QUERY_RESULT =
  | {
      title: null
      intro: null
      seo: null
    }
  | {
      title: string
      intro: null
      seo: null
    }
  | {
      title: string | null
      intro: null
      seo: null
    }
  | {
      title: string
      intro: string | null
      seo: {
        metaTitle: string | null
        metaDescription: string | null
        noIndex: boolean | null
        ogImage: {
          asset: SanityImageAssetReference | null
          hotspot: SanityImageHotspot | null
          crop: SanityImageCrop | null
          alt: string
        } | null
      } | null
    }
  | null

// Source: ../web/sanity/queries.ts
// Variable: HOME_RELEASES_QUERY
// Query: *[_type == "release" && defined(slug.current)]    | order(coalesce(releaseDate, _createdAt) desc)    [0...12]{      _id,      releaseName,      "slug": slug.current,      format,      releaseDate,      dateUnknown,      "artist": artist->{name, "slug": slug.current},      cover{asset, hotspot, crop, alt}    }
export type HOME_RELEASES_QUERY_RESULT = Array<{
  _id: string
  releaseName: string
  slug: string
  format: 'EP' | 'LP' | 'Single'
  releaseDate: string | null
  dateUnknown: boolean | null
  artist: {
    name: string
    slug: string
  }
  cover: {
    asset: SanityImageAssetReference | null
    hotspot: SanityImageHotspot | null
    crop: SanityImageCrop | null
    alt: string
  } | null
}>

// Source: ../web/sanity/queries.ts
// Variable: RELEASES_QUERY
// Query: *[_type == "release" && defined(slug.current)]    | order(coalesce(releaseDate, _createdAt) desc){      _id,      releaseName,      "slug": slug.current,      format,      releaseDate,      dateUnknown,      "artist": artist->{name, "slug": slug.current},      cover{asset, hotspot, crop, alt}    }
export type RELEASES_QUERY_RESULT = Array<{
  _id: string
  releaseName: string
  slug: string
  format: 'EP' | 'LP' | 'Single'
  releaseDate: string | null
  dateUnknown: boolean | null
  artist: {
    name: string
    slug: string
  }
  cover: {
    asset: SanityImageAssetReference | null
    hotspot: SanityImageHotspot | null
    crop: SanityImageCrop | null
    alt: string
  } | null
}>

// Source: ../web/sanity/queries.ts
// Variable: RELEASE_SLUGS_QUERY
// Query: *[_type == "release" && defined(slug.current)][].slug.current
export type RELEASE_SLUGS_QUERY_RESULT = Array<string>

// Source: ../web/sanity/queries.ts
// Variable: RELEASE_QUERY
// Query: *[_type == "release" && slug.current == $slug][0]{    _id,    releaseName,    "slug": slug.current,    format,    speed,    releaseDate,    dateUnknown,    noLabel,    "artist": artist->{name, "slug": slug.current},    "label": label->{name, "slug": slug.current},    cover{asset, hotspot, crop, alt, caption},    gallery[]{_key, asset, hotspot, crop, alt, caption},    discs[]{      _key,      discNumber,      name,      tracks[]{_key, position, title}    },    discogs{releaseId, masterId}  }
export type RELEASE_QUERY_RESULT = {
  _id: string
  releaseName: string
  slug: string
  format: 'EP' | 'LP' | 'Single'
  speed: '33' | '45' | '78'
  releaseDate: string | null
  dateUnknown: boolean | null
  noLabel: boolean | null
  artist: {
    name: string
    slug: string
  }
  label: {
    name: string
    slug: string
  } | null
  cover: {
    asset: SanityImageAssetReference | null
    hotspot: SanityImageHotspot | null
    crop: SanityImageCrop | null
    alt: string
    caption: string | null
  } | null
  gallery: Array<{
    _key: string
    asset: SanityImageAssetReference | null
    hotspot: SanityImageHotspot | null
    crop: SanityImageCrop | null
    alt: string
    caption: string | null
  }> | null
  discs: Array<{
    _key: string
    discNumber: number
    name: string | null
    tracks: Array<{
      _key: string
      position: string
      title: string
    }> | null
  }> | null
  discogs: {
    releaseId: number | null
    masterId: number | null
  } | null
} | null

// Source: ../web/sanity/queries.ts
// Variable: ARTIST_SLUGS_QUERY
// Query: *[_type == "artist" && defined(slug.current)][].slug.current
export type ARTIST_SLUGS_QUERY_RESULT = Array<string>

// Source: ../web/sanity/queries.ts
// Variable: ARTIST_QUERY
// Query: *[_type == "artist" && slug.current == $slug][0]{    _id,    name,    "slug": slug.current,    cover{asset, hotspot, crop, alt, caption},    gallery[]{_key, asset, hotspot, crop, alt, caption},    "releases": *[_type == "release" && artist._ref == ^._id && defined(slug.current)]      | order(coalesce(releaseDate, _createdAt) desc){        _id,        releaseName,        "slug": slug.current,        format,        releaseDate,        dateUnknown,        cover{asset, hotspot, crop, alt}      }  }
export type ARTIST_QUERY_RESULT = {
  _id: string
  name: string
  slug: string
  cover: {
    asset: SanityImageAssetReference | null
    hotspot: SanityImageHotspot | null
    crop: SanityImageCrop | null
    alt: string
    caption: string | null
  } | null
  gallery: Array<{
    _key: string
    asset: SanityImageAssetReference | null
    hotspot: SanityImageHotspot | null
    crop: SanityImageCrop | null
    alt: string
    caption: string | null
  }> | null
  releases: Array<{
    _id: string
    releaseName: string
    slug: string
    format: 'EP' | 'LP' | 'Single'
    releaseDate: string | null
    dateUnknown: boolean | null
    cover: {
      asset: SanityImageAssetReference | null
      hotspot: SanityImageHotspot | null
      crop: SanityImageCrop | null
      alt: string
    } | null
  }>
} | null

// Source: ../web/sanity/queries.ts
// Variable: LABEL_SLUGS_QUERY
// Query: *[_type == "label" && defined(slug.current)][].slug.current
export type LABEL_SLUGS_QUERY_RESULT = Array<string>

// Source: ../web/sanity/queries.ts
// Variable: LABEL_QUERY
// Query: *[_type == "label" && slug.current == $slug][0]{    _id,    name,    "slug": slug.current,    cover{asset, hotspot, crop, alt, caption},    gallery[]{_key, asset, hotspot, crop, alt, caption},    "releases": *[_type == "release" && label._ref == ^._id && defined(slug.current)]      | order(coalesce(releaseDate, _createdAt) desc){        _id,        releaseName,        "slug": slug.current,        format,        releaseDate,        dateUnknown,        "artist": artist->{name, "slug": slug.current},        cover{asset, hotspot, crop, alt}      }  }
export type LABEL_QUERY_RESULT = {
  _id: string
  name: string
  slug: string
  cover: {
    asset: SanityImageAssetReference | null
    hotspot: SanityImageHotspot | null
    crop: SanityImageCrop | null
    alt: string
    caption: string | null
  } | null
  gallery: Array<{
    _key: string
    asset: SanityImageAssetReference | null
    hotspot: SanityImageHotspot | null
    crop: SanityImageCrop | null
    alt: string
    caption: string | null
  }> | null
  releases: Array<{
    _id: string
    releaseName: string
    slug: string
    format: 'EP' | 'LP' | 'Single'
    releaseDate: string | null
    dateUnknown: boolean | null
    artist: {
      name: string
      slug: string
    }
    cover: {
      asset: SanityImageAssetReference | null
      hotspot: SanityImageHotspot | null
      crop: SanityImageCrop | null
      alt: string
    } | null
  }>
} | null

// Query TypeMap
import '@sanity/client'
declare module '@sanity/client' {
  interface SanityQueries {
    '\n  *[_id == "siteSettings"][0]{\n    title,\n    "navigation": coalesce(navigation, [])[]{\n      _key,\n      label,\n      linkType,\n      externalUrl,\n      "internal": internalLink->{\n        _type,\n        "slug": slug.current\n      }\n    }\n  }\n': SITE_SETTINGS_QUERY_RESULT
    '\n  *[_id == "releasesPage"][0]{\n    title,\n    intro,\n    seo{\n      metaTitle,\n      metaDescription,\n      noIndex,\n      ogImage{\n        asset,\n        hotspot,\n        crop,\n        alt\n      }\n    }\n  }\n': RELEASES_PAGE_QUERY_RESULT
    '\n  *[_type == "release" && defined(slug.current)]\n    | order(coalesce(releaseDate, _createdAt) desc)\n    [0...12]{\n      _id,\n      releaseName,\n      "slug": slug.current,\n      format,\n      releaseDate,\n      dateUnknown,\n      "artist": artist->{name, "slug": slug.current},\n      cover{asset, hotspot, crop, alt}\n    }\n': HOME_RELEASES_QUERY_RESULT
    '\n  *[_type == "release" && defined(slug.current)]\n    | order(coalesce(releaseDate, _createdAt) desc){\n      _id,\n      releaseName,\n      "slug": slug.current,\n      format,\n      releaseDate,\n      dateUnknown,\n      "artist": artist->{name, "slug": slug.current},\n      cover{asset, hotspot, crop, alt}\n    }\n': RELEASES_QUERY_RESULT
    '\n  *[_type == "release" && defined(slug.current)][].slug.current\n': RELEASE_SLUGS_QUERY_RESULT
    '\n  *[_type == "release" && slug.current == $slug][0]{\n    _id,\n    releaseName,\n    "slug": slug.current,\n    format,\n    speed,\n    releaseDate,\n    dateUnknown,\n    noLabel,\n    "artist": artist->{name, "slug": slug.current},\n    "label": label->{name, "slug": slug.current},\n    cover{asset, hotspot, crop, alt, caption},\n    gallery[]{_key, asset, hotspot, crop, alt, caption},\n    discs[]{\n      _key,\n      discNumber,\n      name,\n      tracks[]{_key, position, title}\n    },\n    discogs{releaseId, masterId}\n  }\n': RELEASE_QUERY_RESULT
    '\n  *[_type == "artist" && defined(slug.current)][].slug.current\n': ARTIST_SLUGS_QUERY_RESULT
    '\n  *[_type == "artist" && slug.current == $slug][0]{\n    _id,\n    name,\n    "slug": slug.current,\n    cover{asset, hotspot, crop, alt, caption},\n    gallery[]{_key, asset, hotspot, crop, alt, caption},\n    "releases": *[_type == "release" && artist._ref == ^._id && defined(slug.current)]\n      | order(coalesce(releaseDate, _createdAt) desc){\n        _id,\n        releaseName,\n        "slug": slug.current,\n        format,\n        releaseDate,\n        dateUnknown,\n        cover{asset, hotspot, crop, alt}\n      }\n  }\n': ARTIST_QUERY_RESULT
    '\n  *[_type == "label" && defined(slug.current)][].slug.current\n': LABEL_SLUGS_QUERY_RESULT
    '\n  *[_type == "label" && slug.current == $slug][0]{\n    _id,\n    name,\n    "slug": slug.current,\n    cover{asset, hotspot, crop, alt, caption},\n    gallery[]{_key, asset, hotspot, crop, alt, caption},\n    "releases": *[_type == "release" && label._ref == ^._id && defined(slug.current)]\n      | order(coalesce(releaseDate, _createdAt) desc){\n        _id,\n        releaseName,\n        "slug": slug.current,\n        format,\n        releaseDate,\n        dateUnknown,\n        "artist": artist->{name, "slug": slug.current},\n        cover{asset, hotspot, crop, alt}\n      }\n  }\n': LABEL_QUERY_RESULT
  }
}
